name: pmob2_kelompok_uas
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  http: ^1.3.0
  intl: ^0.20.2
  lottie: ^3.2.0
  lucide_icons: ^0.257.0
  mobile_scanner: ^6.0.6
  qr_code_scanner: ^1.0.1
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/
